export const MODULO_ROUTES: Record<string, string> = {
  dashboard: '/dashboard',
  minha_empresa: '/configuracoes/empresa',
  configuracoes: '/configuracoes',
  'meus-modulos': '/meus-modulos',
  crm: '/crm/dashboard',
  estoque: '/estoque/dashboard',
  vendas: '/vendas',
  loja_virtual: '/marketplace',
  agenda: '/agenda',
  financeiro: '/financeiro/dashboard',
  metricas: '/metricas/dashboard',
  mel: '/mel',
  chatbot: '/chatbot',
  marketplace: '/marketplace',
  fornecedores: '/fornecedores',
  servicos: '/servicos',
  colaboradores: '/configuracoes/colaboradores',
};
