import { FormEvent, useMemo, useState } from "react";
import { AlertCircle, Calendar, Check, CheckCircle, Clock, Edit, MessageCircle, Plus, Search, Trash2, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { calcularDiasVencimento, calcularStatus, ContaReceber, contasReceberMock, formatarMoeda, StatusMovimentacao } from "./mockData";

const hoje = () => new Date().toISOString().slice(0, 10);
const labels: Record<StatusMovimentacao, string> = { pago: "Recebido", pendente: "A receber", vencido: "Atrasado" };
function StatusBadge({ status }: { status: StatusMovimentacao }) { return <span className="inline-flex items-center gap-1 rounded-full border border-[#627271] px-2 py-1 text-xs font-medium"><span className="h-1.5 w-1.5 rounded-full bg-[#86cb92]" />{labels[status]}</span>; }

export function ContasReceberPage() {
  const [contas, setContas] = useState<ContaReceber[]>(contasReceberMock);
  const [filtroStatus, setFiltroStatus] = useState<StatusMovimentacao | "todos">("todos");
  const [busca, setBusca] = useState("");
  const [modal, setModal] = useState<"nova" | "editar" | "receber" | "cobranca" | null>(null);
  const [selecionada, setSelecionada] = useState<ContaReceber | null>(null);
  const [feedback, setFeedback] = useState("");
  const comStatus = useMemo(() => contas.map(c => ({ ...c, status: calcularStatus(c.dataPrevista, c.status) })), [contas]);
  const filtradas = comStatus.filter(c => (filtroStatus === "todos" || c.status === filtroStatus) && `${c.descricao} ${c.cliente}`.toLowerCase().includes(busca.toLowerCase()));
  const total = (status: StatusMovimentacao) => comStatus.filter(c => c.status === status).reduce((s, c) => s + c.valor, 0);
  const avisar = (text: string) => { setFeedback(text); window.setTimeout(() => setFeedback(""), 3200); };
  const fechar = () => { setModal(null); setSelecionada(null); };
  const salvar = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const conta: ContaReceber = { id: selecionada?.id || `receber-local-${Date.now()}`, cliente: String(data.get("cliente")), descricao: String(data.get("descricao")), categoria: String(data.get("categoria")) as ContaReceber["categoria"], valor: Number(data.get("valor")), dataPrevista: String(data.get("data")), status: selecionada?.status || "pendente", formaPagamento: (String(data.get("forma")) || undefined) as ContaReceber["formaPagamento"] }; setContas(items => selecionada ? items.map(item => item.id === conta.id ? conta : item) : [conta, ...items]); fechar(); avisar(selecionada ? "Conta atualizada." : "Conta criada com sucesso."); };
  const receber = () => { if (!selecionada) return; setContas(items => items.map(item => item.id === selecionada.id ? { ...item, status: "pago" } : item)); fechar(); avisar("Recebimento registrado com sucesso."); };
  const excluir = (conta: ContaReceber) => { if (window.confirm(`Excluir a conta de ${conta.cliente}?`)) { setContas(items => items.filter(item => item.id !== conta.id)); avisar("Conta excluída."); } };

  return <main data-od-id="contas-receber-regiao" className="mx-auto max-w-7xl p-4 text-[#1f2937] sm:p-6">
    <header className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 data-od-id="contas-receber-heading" className="mb-1 text-2xl font-semibold">Contas a Receber</h1><p className="text-sm text-[#627271]">Acompanhe pagamentos de clientes e parcelas pendentes.</p></div><button data-od-id="contas-receber-cta" onClick={() => setModal("nova")} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#86cb92] px-4 py-2.5 text-sm font-semibold hover:bg-[#1f2937] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]"><Plus size={18} />Nova conta</button></header>
    {feedback && <div role="status" className="mb-4 flex items-center gap-2 rounded-lg border border-[#627271] bg-[#efefef] p-3 text-sm"><Check size={17} />{feedback}</div>}
    <section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{([["Total a receber", total("pendente"), Clock], ["Total em atraso", total("vencido"), AlertCircle], ["Total recebido", total("pago"), CheckCircle], ["Previsão de receita", total("pendente") + total("vencido"), Clock]] as [string, number, LucideIcon][]).map(([label, value, Icon]) => <div key={label} className="rounded-lg border border-[#efefef] bg-white p-4"><div className="mb-4 flex items-center justify-between"><span className="text-sm text-[#627271]">{label}</span><span className="rounded-lg bg-[#efefef] p-2"><Icon size={18} /></span></div><strong className="text-2xl">{formatarMoeda(value)}</strong></div>)}</section>
    <section data-od-id="contas-receber-filtros" className="mb-6 rounded-lg border border-[#efefef] bg-white p-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Status<select value={filtroStatus} onChange={e => setFiltroStatus(e.target.value as StatusMovimentacao | "todos")} className="mt-1.5 w-full rounded-lg border border-[#627271] bg-white px-3 py-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#86cb92]"><option value="todos">Todos</option><option value="pendente">A receber</option><option value="pago">Recebidos</option><option value="vencido">Atrasados</option></select></label><label className="text-sm font-medium">Buscar<input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Descrição ou cliente" className="mt-1.5 w-full rounded-lg border border-[#627271] px-3 py-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#86cb92]" /></label></div></section>
    <section data-od-id="contas-receber-tabela" className="overflow-hidden rounded-lg border border-[#efefef] bg-white"><div className="border-b border-[#efefef] p-4"><h2 className="font-semibold">Contas cadastradas <span className="text-sm font-normal text-[#627271]">({filtradas.length})</span></h2></div>{filtradas.length === 0 ? <div className="p-10 text-center"><Search className="mx-auto mb-3" /><h3 className="font-semibold">Nenhuma conta encontrada</h3><p className="mt-1 text-sm text-[#627271]">Ajuste os filtros ou cadastre um novo recebimento.</p></div> : <table className="w-full table-fixed text-left text-sm"><thead className="bg-[#efefef] text-xs"><tr><th className="w-[18%] px-3 py-3">Cliente</th><th className="w-[24%] px-3 py-3">Descrição</th><th className="w-[16%] px-3 py-3">Data prevista</th><th className="w-[14%] px-3 py-3 text-right">Valor</th><th className="w-[14%] px-3 py-3 text-center">Status</th><th className="w-[18%] px-3 py-3 text-center">Ações</th></tr></thead><tbody>{filtradas.map(conta => <tr data-od-id="contas-receber-linha" key={conta.id} className="border-t border-[#efefef] align-middle hover:bg-[#efefef]"><td className="break-words px-3 py-3 font-medium">{conta.cliente}{conta.formaPagamento && <span className="block text-xs font-normal text-[#627271]">{conta.formaPagamento}</span>}</td><td className="break-words px-3 py-3">{conta.descricao}{conta.parcela && <span className="block text-xs text-[#627271]">Parcela {conta.parcela}</span>}</td><td className="px-3 py-3"><span className="flex items-center gap-1"><Calendar size={14} />{new Date(conta.dataPrevista).toLocaleDateString("pt-BR")}</span><span className="text-xs text-[#627271]">{calcularDiasVencimento(conta.dataPrevista) < 0 && conta.status !== "pago" ? "Em atraso" : "No prazo"}</span></td><td className="px-3 py-3 text-right font-semibold">{formatarMoeda(conta.valor)}</td><td className="px-3 py-3 text-center"><StatusBadge status={conta.status} /></td><td className="px-2 py-3"><div className="flex flex-wrap justify-center gap-1">{conta.status !== "pago" && <><button onClick={() => { setSelecionada(conta); setModal("receber"); }} className="rounded-lg border border-[#627271] px-2 py-1 text-xs font-medium hover:bg-[#86cb92]">Receber</button>{conta.status === "vencido" && <button aria-label="Demonstrar cobrança" onClick={() => { setSelecionada(conta); setModal("cobranca"); }} className="rounded-lg border border-[#627271] p-1.5 hover:bg-[#efefef]"><MessageCircle size={15} /></button>}</>}<button aria-label="Editar" onClick={() => { setSelecionada(conta); setModal("editar"); }} className="rounded-lg p-1.5 hover:bg-[#efefef]"><Edit size={16} /></button><button aria-label="Excluir" onClick={() => excluir(conta)} className="rounded-lg p-1.5 hover:bg-[#efefef]"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>}</section>
    {(modal === "nova" || modal === "editar") && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1f2937]/70 p-4"><div data-od-id="contas-receber-modal" role="dialog" aria-modal="true" className="w-full max-w-lg rounded-lg bg-white p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{modal === "editar" ? "Editar conta a receber" : "Nova conta a receber"}</h2><button onClick={fechar} aria-label="Fechar" className="rounded-lg p-1 hover:bg-[#efefef]"><X size={20} /></button></div><form onSubmit={salvar} className="space-y-3"><label className="block text-sm font-medium">Cliente<input required name="cliente" defaultValue={selecionada?.cliente} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><label className="block text-sm font-medium">Descrição<input required name="descricao" defaultValue={selecionada?.descricao} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Valor<input required min="0.01" step="0.01" type="number" name="valor" defaultValue={selecionada?.valor} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><label className="text-sm font-medium">Data prevista<input required type="date" name="data" defaultValue={selecionada?.dataPrevista || hoje()} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Categoria<input required name="categoria" defaultValue={selecionada?.categoria || "Vendas"} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><label className="text-sm font-medium">Forma de pagamento<select name="forma" defaultValue={selecionada?.formaPagamento || "PIX"} className="mt-1 block w-full rounded-lg border border-[#627271] bg-white px-3 py-2"><option>PIX</option><option>Dinheiro</option><option>Boleto</option><option>Transferência</option><option>Cartão</option></select></label></div><button className="w-full rounded-lg bg-[#86cb92] px-4 py-2.5 font-semibold hover:bg-[#1f2937] hover:text-white">Salvar conta</button></form></div></div>}
    {modal === "receber" && selecionada && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1f2937]/70 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-lg bg-white p-5"><h2 className="mb-2 text-lg font-semibold">Registrar recebimento</h2><p className="mb-5 text-sm text-[#627271]">Confirmar recebimento de <strong className="text-[#1f2937]">{selecionada.cliente}</strong> no valor de {formatarMoeda(selecionada.valor)}?</p><div className="flex gap-2"><button onClick={fechar} className="flex-1 rounded-lg border border-[#627271] px-4 py-2">Cancelar</button><button onClick={receber} className="flex-1 rounded-lg bg-[#86cb92] px-4 py-2 font-semibold">Confirmar</button></div></div></div>}
    {modal === "cobranca" && selecionada && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1f2937]/70 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-lg bg-white p-5"><h2 className="mb-2 text-lg font-semibold">Demonstrar cobrança</h2><p className="mb-4 text-sm text-[#627271]">Esta é uma simulação. Nenhuma mensagem será enviada.</p><div className="mb-5 rounded-lg border border-[#627271] bg-[#efefef] p-3 text-sm">Olá, {selecionada.cliente}. Lembrete sobre o pagamento de {formatarMoeda(selecionada.valor)} referente a {selecionada.descricao}.</div><button onClick={() => { fechar(); avisar("Cobrança demonstrada — nenhuma mensagem foi enviada."); }} className="w-full rounded-lg bg-[#86cb92] px-4 py-2.5 font-semibold">Entendi</button></div></div>}
  </main>;
}
