import { FormEvent, useMemo, useState } from "react";
import { AlertCircle, Calendar, Check, CheckCircle, Clock, Edit, Plus, Search, Trash2, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { contasPagarMock, calcularDiasVencimento, calcularStatus, ContaPagar, formatarMoeda, StatusMovimentacao } from "./mockData";

const hoje = () => new Date().toISOString().slice(0, 10);
const statusLabel: Record<StatusMovimentacao, string> = { pago: "Pago", pendente: "Pendente", vencido: "Vencido" };

function StatusBadge({ status }: { status: StatusMovimentacao }) {
  return <span className="inline-flex items-center gap-1 rounded-full border border-[#627271] px-2 py-1 text-xs font-medium text-[#1f2937]"><span className="h-1.5 w-1.5 rounded-full bg-[#86cb92]" />{statusLabel[status]}</span>;
}

export function ContasPagarPage() {
  const [contas, setContas] = useState<ContaPagar[]>(contasPagarMock);
  const [filtroStatus, setFiltroStatus] = useState<StatusMovimentacao | "todos">("todos");
  const [busca, setBusca] = useState("");
  const [modalAberto, setModalAberto] = useState(false);
  const [editando, setEditando] = useState<ContaPagar | null>(null);
  const [pagando, setPagando] = useState<ContaPagar | null>(null);
  const [feedback, setFeedback] = useState("");

  const comStatus = useMemo(() => contas.map(c => ({ ...c, status: calcularStatus(c.dataVencimento, c.status) })), [contas]);
  const filtradas = comStatus.filter(c => (filtroStatus === "todos" || c.status === filtroStatus) && `${c.descricao} ${c.fornecedor}`.toLowerCase().includes(busca.toLowerCase()));
  const total = (status: StatusMovimentacao) => comStatus.filter(c => c.status === status).reduce((s, c) => s + c.valor, 0);
  const fechar = () => { setModalAberto(false); setEditando(null); setPagando(null); };
  const avisar = (texto: string) => { setFeedback(texto); window.setTimeout(() => setFeedback(""), 3200); };
  const salvar = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const conta: ContaPagar = { id: editando?.id || `pagar-local-${Date.now()}`, descricao: String(data.get("descricao")), fornecedor: String(data.get("fornecedor")), categoria: String(data.get("categoria")) as ContaPagar["categoria"], valor: Number(data.get("valor")), dataVencimento: String(data.get("data")), status: editando?.status || "pendente", recorrente: data.get("recorrente") === "on" };
    setContas(items => editando ? items.map(item => item.id === conta.id ? conta : item) : [conta, ...items]);
    fechar(); avisar(editando ? "Conta atualizada." : "Conta criada com sucesso.");
  };
  const registrarPagamento = () => {
    if (!pagando) return;
    setContas(items => items.map(item => item.id === pagando.id ? { ...item, status: "pago" } : item));
    fechar(); avisar("Pagamento registrado com sucesso.");
  };
  const excluir = (conta: ContaPagar) => { if (window.confirm(`Excluir a conta “${conta.descricao}”?`)) { setContas(items => items.filter(item => item.id !== conta.id)); avisar("Conta excluída."); } };

  return <main data-od-id="contas-pagar-regiao" className="mx-auto max-w-7xl p-4 text-[#1f2937] sm:p-6">
    <header className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
      <div><h1 data-od-id="contas-pagar-heading" className="mb-1 text-2xl font-semibold">Contas a Pagar</h1><p className="text-sm text-[#627271]">Organize despesas, prazos e pagamentos do seu negócio.</p></div>
      <button data-od-id="contas-pagar-cta" onClick={() => { setEditando(null); setModalAberto(true); }} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#86cb92] px-4 py-2.5 text-sm font-semibold transition hover:bg-[#1f2937] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1f2937]"><Plus size={18} />Nova conta</button>
    </header>
    {feedback && <div role="status" className="mb-4 flex items-center gap-2 rounded-lg border border-[#627271] bg-[#efefef] p-3 text-sm"><Check size={17} />{feedback}</div>}
    <section className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Indicadores financeiros">
      {([["Total a pagar", total("pendente"), Clock], ["Total vencido", total("vencido"), AlertCircle], ["Total pago", total("pago"), CheckCircle], ["Contas pendentes", comStatus.filter(c => c.status === "pendente").length, Clock]] as [string, number, LucideIcon][]).map(([label, value, Icon]) => <div key={label} className="rounded-lg border border-[#efefef] bg-white p-4"><div className="mb-4 flex items-center justify-between"><span className="text-sm text-[#627271]">{label}</span><span className="rounded-lg bg-[#efefef] p-2"><Icon size={18} /></span></div><strong className="text-2xl">{label === "Contas pendentes" ? value : formatarMoeda(value)}</strong></div>)}
    </section>
    <section data-od-id="contas-pagar-filtros" className="mb-6 rounded-lg border border-[#efefef] bg-white p-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Status<select value={filtroStatus} onChange={e => setFiltroStatus(e.target.value as StatusMovimentacao | "todos")} className="mt-1.5 w-full rounded-lg border border-[#627271] bg-white px-3 py-2 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#86cb92]"><option value="todos">Todos</option><option value="pendente">Pendentes</option><option value="pago">Pagas</option><option value="vencido">Vencidas</option></select></label><label className="text-sm font-medium">Buscar<input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Descrição ou fornecedor" className="mt-1.5 w-full rounded-lg border border-[#627271] px-3 py-2 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#86cb92]" /></label></div></section>
    <section data-od-id="contas-pagar-tabela" className="overflow-hidden rounded-lg border border-[#efefef] bg-white"><div className="border-b border-[#efefef] p-4"><h2 className="font-semibold">Contas cadastradas <span className="text-sm font-normal text-[#627271]">({filtradas.length})</span></h2></div>{filtradas.length === 0 ? <div className="p-10 text-center"><Search className="mx-auto mb-3" /><h3 className="font-semibold">Nenhuma conta encontrada</h3><p className="mt-1 text-sm text-[#627271]">Ajuste os filtros ou cadastre uma nova conta.</p></div> : <table className="w-full table-fixed text-left text-sm"><thead className="bg-[#efefef] text-xs"><tr><th className="w-[24%] px-3 py-3">Descrição</th><th className="w-[18%] px-3 py-3">Fornecedor</th><th className="hidden px-3 py-3 md:table-cell">Categoria</th><th className="w-[14%] px-3 py-3">Vencimento</th><th className="w-[13%] px-3 py-3 text-right">Valor</th><th className="w-[14%] px-3 py-3 text-center">Status</th><th className="w-[17%] px-3 py-3 text-center">Ações</th></tr></thead><tbody>{filtradas.map(conta => <tr data-od-id="contas-pagar-linha" key={conta.id} className="border-t border-[#efefef] align-middle hover:bg-[#efefef]"><td className="break-words px-3 py-3 font-medium">{conta.descricao}{conta.recorrente && <span className="block text-xs font-normal text-[#627271]">Recorrente</span>}</td><td className="break-words px-3 py-3">{conta.fornecedor}</td><td className="hidden px-3 py-3 md:table-cell">{conta.categoria}</td><td className="px-3 py-3"><span className="flex items-center gap-1"><Calendar size={14} />{new Date(conta.dataVencimento).toLocaleDateString("pt-BR")}</span><span className="text-xs text-[#627271]">{calcularDiasVencimento(conta.dataVencimento) < 0 && conta.status !== "pago" ? "Em atraso" : "No prazo"}</span></td><td className="px-3 py-3 text-right font-semibold">{formatarMoeda(conta.valor)}</td><td className="px-3 py-3 text-center"><StatusBadge status={conta.status} /></td><td className="px-2 py-3"><div className="flex flex-wrap justify-center gap-1">{conta.status !== "pago" && <button onClick={() => setPagando(conta)} className="rounded-lg border border-[#627271] px-2 py-1 text-xs font-medium hover:bg-[#86cb92] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]">Pagar</button>}<button aria-label="Editar" onClick={() => { setEditando(conta); setModalAberto(true); }} className="rounded-lg p-1.5 hover:bg-[#efefef] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]"><Edit size={16} /></button><button aria-label="Excluir" onClick={() => excluir(conta)} className="rounded-lg p-1.5 hover:bg-[#efefef] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>}</section>
    {modalAberto && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1f2937]/70 p-4"><div data-od-id="contas-pagar-modal" role="dialog" aria-modal="true" className="w-full max-w-lg rounded-lg bg-white p-5 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{editando ? "Editar conta a pagar" : "Nova conta a pagar"}</h2><button onClick={fechar} aria-label="Fechar" className="rounded-lg p-1 hover:bg-[#efefef] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]"><X size={20} /></button></div><form onSubmit={salvar} className="space-y-3"><label className="block text-sm font-medium">Descrição<input required name="descricao" defaultValue={editando?.descricao} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#86cb92]" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Fornecedor<input required name="fornecedor" defaultValue={editando?.fornecedor} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><label className="text-sm font-medium">Categoria<input required name="categoria" defaultValue={editando?.categoria} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Valor<input required min="0.01" step="0.01" type="number" name="valor" defaultValue={editando?.valor} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label><label className="text-sm font-medium">Vencimento<input required type="date" name="data" defaultValue={editando?.dataVencimento || hoje()} className="mt-1 block w-full rounded-lg border border-[#627271] px-3 py-2" /></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="recorrente" defaultChecked={editando?.recorrente} /> Conta recorrente</label><button className="mt-2 w-full rounded-lg bg-[#86cb92] px-4 py-2.5 font-semibold hover:bg-[#1f2937] hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#1f2937]">Salvar conta</button></form></div></div>}
    {pagando && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#1f2937]/70 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-lg bg-white p-5"><h2 className="mb-2 text-lg font-semibold">Registrar pagamento</h2><p className="mb-5 text-sm text-[#627271]">Confirmar pagamento de <strong className="text-[#1f2937]">{pagando.descricao}</strong> no valor de {formatarMoeda(pagando.valor)}?</p><div className="flex gap-2"><button onClick={fechar} className="flex-1 rounded-lg border border-[#627271] px-4 py-2">Cancelar</button><button onClick={registrarPagamento} className="flex-1 rounded-lg bg-[#86cb92] px-4 py-2 font-semibold">Confirmar</button></div></div></div>}
  </main>;
}
